# @package _global_

# default debugging setup, runs 1 full epoch
# other debugging configs can inherit from this one

defaults:
  - override /neptune: offline # Use local neptune
  - override /paths: local # Use local paths

# overwrite task name so debugging logs are stored in separate folder
task_name: "debug"

# sets level of all command line loggers to 'DEBUG'
# https://hydra.cc/docs/tutorials/basic/running_your_app/logging/
hydra:
  job_logging:
    root:
      level: DEBUG
  # use this to also set hydra loggers to 'DEBUG'
  # verbose: True

steps:
  train:
    trainer:
      max_epochs: 1
      accelerator: cpu # debuggers don't like gpus
      devices: 1 # debuggers don't like multiprocessing
      detect_anomaly: true # raise exception if NaN or +/-inf is detected in any tensor
    bentoml:
      export: False
    data:
      num_workers: 0 # debuggers don't like multiprocessing
      pin_memory: False # disable gpu memory pin
  test:
    trainer:
      ${steps.train.trainer}
    data:
      num_workers: 0 # debuggers don't like multiprocessing
      pin_memory: False # disable gpu memory pin
  convert:
    bentoml:
      export: False
